# 595. Big Countries
# Write your MySQL query statement below
SELECT NAME,POPULATION,AREA
FROM WORLD
WHERE
AREA >= 3000000 OR POPULATION >= 25000000;

# 1148. Article Views I
SELECT DISTINCT(AUTHOR_ID) AS ID
FROM VIEWS
WHERE AUTHOR_ID = VIEWER_ID
ORDER BY AUTHOR_ID ASC;